### ISSUE TITLE
can't download files with @ in key

### ISSUE THREAD

**Issue by torfeld6** [aws/aws-sdk-php#1120]
I'm trying to download a file called close_hi@2x.png with a Aws\S3\Transfer. This only works with the following updated function (added urldecode).

Any ideas how to solve this issue?

```
/**
 * Creates an array that contains Bucket and Key by parsing the filename.
 *
 * @param string $path Path to parse.
 *
 * @return array
 */
private function getS3Args($path)
{
    $parts = explode('/', str_replace('s3://', '', $path), 2);
    $args = ['Bucket' => $parts[0]];
    if (isset($parts[1])) {
        $args['Key'] = urldecode($parts[1]);
    }

    return $args;
}
```

**Comment by cjyclaire** [comment]
@torfeld6 Interestingly, I couldn't reproduce the issue with file names containing '_' or '@', transfer manager works fine for me. Could you provide more information? May I ask the version of the SDK and the version of PHP being used?

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further details or questions

**Comment by torfeld6** [comment]
I'm sorry for the delay, other projects came up.

The full exception:
```{
    "code": 0,
    "file": "/Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php",
    "line": 192,
    "message": "Error executing \"GetObject\" on \"https://s3-eu-west-1.amazonaws.com/pitcherzerodrive/158684/extracted/assets/player/close_hi%25402x.png\"; AWS HTTP error: Client error: `GET https://s3-eu-west-1.amazonaws.com/pitcherzerodrive/158684/extracted/assets/player/close_hi%25402x.png` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)\n NoSuchKey (client): The specified key does not exist. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>158684/extracted/assets/player/close_hi%402x.png</Key><RequestId>361D2C42536A6171</RequestId><HostId>R36PZxWpzlAfwYp4tSkbrcEsascMgRw9IdyUHbxyfSVQRf/+4jhmUEhYcI47u5fBqZpBwFdl6+E=</HostId></Error>",
    "name": "Exception",
    "previous": {
        "code": 404,
        "file": "/Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php",
        "line": 111,
        "message": "Client error: `GET https://s3-eu-west-1.amazonaws.com/pitcherzerodrive/158684/extracted/assets/player/close_hi%25402x.png` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)\n",
        "name": "Exception",
        "stack-trace": [
            "#0 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))",
            "#1 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))",
            "#2 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)",
            "#3 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()",
            "#4 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\\Promise\\TaskQueue->run()",
            "#5 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\\Handler\\CurlMultiHandler->tick()",
            "#6 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)",
            "#7 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
            "#8 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#9 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
            "#10 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#11 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
            "#12 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#13 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\\Promise\\Promise->wait()",
            "#14 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(true)",
            "#15 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
            "#16 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#17 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
            "#18 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#19 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(101): GuzzleHttp\\Promise\\Promise->wait()",
            "#20 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\EachPromise->GuzzleHttp\\Promise\\{closure}(true)",
            "#21 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
            "#22 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
            "#23 /Users/josh/Documents/Workspace/pitcher-zerodrive/models/ExtractedFile.php(75): GuzzleHttp\\Promise\\Promise->wait()",
            "#24 /Users/josh/Documents/Workspace/pitcher-zerodrive/modules/api/controllers/ExtractedFileController.php(52): app\\models\\ExtractedFile->downloadTo('/private/var/tm...')",
            "#25 [internal function]: app\\modules\\api\\controllers\\ExtractedFileController->actionUpload()",
            "#26 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)",
            "#27 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Controller.php(154): yii\\base\\InlineAction->runWithParams(Array)",
            "#28 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Module.php(454): yii\\base\\Controller->runAction('upload', Array)",
            "#29 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/web/Application.php(100): yii\\base\\Module->runAction('api/extracted-f...', Array)",
            "#30 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
            "#31 /Users/josh/Documents/Workspace/pitcher-zerodrive/web/index.php(13): yii\\base\\Application->run()",
            "#32 {main}"
        ],
        "type": "GuzzleHttp\\Exception\\ClientException"
    },
    "stack-trace": [
        "#0 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(102): Aws\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\Psr7\\Request), Object(Aws\\Command), Array)",
        "#1 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\\WrappedHttpHandler->Aws\\{closure}(Array)",
        "#2 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\\Promise\\Promise::callHandler(2, Array, Array)",
        "#3 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}(Array)",
        "#4 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()",
        "#5 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\\Promise\\TaskQueue->run()",
        "#6 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\\Handler\\CurlMultiHandler->tick()",
        "#7 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)",
        "#8 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
        "#9 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#10 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
        "#11 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#12 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
        "#13 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#14 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\\Promise\\Promise->wait()",
        "#15 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(true)",
        "#16 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
        "#17 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#18 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
        "#19 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#20 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(101): GuzzleHttp\\Promise\\Promise->wait()",
        "#21 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\EachPromise->GuzzleHttp\\Promise\\{closure}(true)",
        "#22 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
        "#23 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#24 /Users/josh/Documents/Workspace/pitcher-zerodrive/models/ExtractedFile.php(75): GuzzleHttp\\Promise\\Promise->wait()",
        "#25 /Users/josh/Documents/Workspace/pitcher-zerodrive/modules/api/controllers/ExtractedFileController.php(52): app\\models\\ExtractedFile->downloadTo('/private/var/tm...')",
        "#26 [internal function]: app\\modules\\api\\controllers\\ExtractedFileController->actionUpload()",
        "#27 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)",
        "#28 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Controller.php(154): yii\\base\\InlineAction->runWithParams(Array)",
        "#29 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Module.php(454): yii\\base\\Controller->runAction('upload', Array)",
        "#30 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/web/Application.php(100): yii\\base\\Module->runAction('api/extracted-f...', Array)",
        "#31 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#32 /Users/josh/Documents/Workspace/pitcher-zerodrive/web/index.php(13): yii\\base\\Application->run()",
        "#33 {main}"
    ],
    "type": "Aws\\S3\\Exception\\S3Exception"
}
```

And this is my code:
```
    public function addFilesAsync($source)
    {
        $client = getS3Client(\Yii::$app->params["s3"]["pitcher"]);
        $bucket = \Yii::$app->params["s3"]["pitcher"]["bucket"];
        $dest = "s3://$bucket/$this->ID/extracted/";
        $manager = new Transfer($client, $source, $dest);
        return $manager->promise();
    }
```

helpers.php
```
function getS3Client($config, $bucket = null)
{
    if ($bucket) $config["bucket"] = $bucket;
    return (new \Aws\Sdk)->createMultiRegionS3($config);
}
```

params.php
```
    's3' => [
    	'bucket' => 'pitcherzerodrive',
		'pitcher' => [
    		'bucket' => 'pitcherzerodrive',
		    'version' => 'latest',
		    'credentials' => [
		        'key'    => '<key>',
		        'secret' => '<secret>',
		    ],
		    'http'    => [
		        'verify' => false
		    ]
		]
```

the file on S3: 
![screen shot 2016-11-29 at 14 55 04](https://cloud.githubusercontent.com/assets/661673/20712355/f8a18562-b643-11e6-9637-938fc92bbcf7.png)

sdk version:
```
aws/aws-sdk-php              3.19.32 AWS SDK for PHP - Use Amazon Web Services in your PHP project
```

**Comment by torfeld6** [comment]
the url encode hack I posted first doesn't work, because the downloaded file names are url encoded. a diff of both folders (SVf3TT = downloaded, before = original):
```
Only in SVf3TT/assets/player: close_hi%402x.png
Only in before/assets/player: close_hi@2x.png
Only in SVf3TT/assets/player: close_n%402x.png
Only in before/assets/player: close_n@2x.png
Only in SVf3TT/assets/player: close_p%402x.png
Only in before/assets/player: close_p@2x.png
```

**Comment by torfeld6** [comment]
I realised it encoded the @ twice. @ -> %40 -> %2540. Hope it helps

**Comment by torfeld6** [comment]
New quick and dirty fix that works for me:
```
S3/Tansfer.php Line 284
/** @return Iterator */
private function getDownloadsIterator()
{
    if (is_string($this->source)) {
        $listArgs = $this->getS3Args($this->sourceMetadata['path']);
        if (isset($listArgs['Key'])) {
            $listArgs['Prefix'] = $listArgs['Key'] . '/';
            unset($listArgs['Key']);
        }

        $files = $this->client
            ->getPaginator('ListObjects', $listArgs)
            ->search('Contents[].Key');
        $files = Aws\map($files, function ($key) use ($listArgs) {
            return "s3://{$listArgs['Bucket']}/" . urldecode($key);
        });
        return Aws\filter($files, function ($key) {
            return substr($key, -1, 1) !== '/';
        });
    }

    return $this->source;
}
```

The cause of the issue is the following returns a list of  encoded instead of decoded urls:
```
S3/Tansfer.php Line 294
$files = $this->client
                ->getPaginator('ListObjects', $listArgs)
                ->search('Contents[].Key');
```

**Comment by cjyclaire** [comment]
@torfeld6 Taking a look ...

**Comment by cjyclaire** [comment]
@torfeld6 Really appreciate your input there! And I really hope to reproduce possible bug there and fix it. However I still have trouble in reproducing the issue there. I tried both upload a local directory to s3 or download a directory from s3 to my local disk. Both source contains a exactly same file name "close_hi@zx.png", and both result looks good with correct name "close_hi@zx.png". 
Could you give more information that could help me to reproduce the issue?

**Comment by jbruni** [comment]
I am also having troubles related to encoding of file names... I am using the stream wrapper, and the same code works for "regular" key names (ASCII chars), but fails for keys like `Seleção_04.jpg`.

Something "URL encodes" the key name and the result is an exception.

**Comment by jbruni** [comment]
The relevant part of my code is as follows:

```php
    $s3Client = new \Aws\S3\S3Client([
        // settings here
    ]);
    $s3Client->registerStreamWrapper();

    $s3Prefix = 's3://' . $bucket . '/';
    $context = stream_context_create([
        's3' => ['seekable' => true]
    ]);

    $stream = fopen($s3Prefix . $key, 'r', false, $context);
    // read operations
    fclose($stream);
```

**Comment by jbruni** [comment]
To reproduce, I suggest uploading a file with such name (`Seleção_01.png`, for example), and then trying to access it using the code snippet above. It is fairly simple.

**Comment by jbruni** [comment]
Nevermind... in my case, the `$key` I was passing was already "url encoded", so the issue was before hitting AWS SDK. And the solution was as easy as applying a `urldecode` to it.
