### ISSUE TITLE
DynamoDB putItem returns SerializationException when data contains UTF8 characters

### ISSUE THREAD

**Issue by NeilJ247** [aws/aws-sdk-php#1536]
I believe this is the same issue reported a while back for the JS version of the SDK but I am seeing it for the PHP version as well: https://github.com/aws/aws-sdk-js/issues/46

I am using the latest version of the SDK (3.55.1).  The UTF8 characters are ú and á.  They are being set in string and map values.  We are using the Marshaler::marshalItem when calling putItem so maybe something around this area?  Not sure.

Any other info required then give me a shout.

Thanks.

**Comment by kstich** [comment]
Can you please provide a code sample for how you're doing the `putItem` request via the `Marshaler`, as well as the specific error you're receiving?

**Comment by NeilJ247** [comment]
Example:

```
$itemData = [
   "key1" => "Jesús", 
   "key2" => [
       "key3" => "Jesús"
    ]
];

$itemMarshaller = $this->getMarshaler();
return $this->getDynamoDb()->putItem(
    [
        'TableName' => $this->getTableName(),
        'Item' => $itemMarshaller->marshalItem($itemData),
    ]
);
```

Exception:

```
Uncaught PHP Exception Aws\DynamoDb\Exception\DynamoDbException: "Error executing "PutItem" on "https://dynamodb.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `PO
ST https://dynamodb.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.service#SerializationException"}
 SerializationException (client):  - {"__type":"com.amazon.coral.service#SerializationException"}" at /html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php line 192 Array
(
    [exception] => [object] (Aws\DynamoDb\Exception\DynamoDbException(code: 0): Error executing "PutItem" on "https://dynamodb.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.eu-wes
t-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.service#SerializationException"}
 SerializationException (client):  - {"__type":"com.amazon.coral.service#SerializationException"} at /html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:192, GuzzleHttp\Exception\ClientException(code: 400): C
lient error: `POST https://dynamodb.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.service#SerializationException"}
 at /html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(101): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /html/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /html/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#3 /html/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#6 /html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /html/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /html/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /html/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /html/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /html/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /html/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait()
#15 /html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command))
#16 /html/vendor/misha/audit-logger-bundle/src/Maglabs/Misha/AuditLoggerBundle/AuditLogger.php(188): Aws\AwsClient->__call('putItem', Array)
```

**Comment by howardlopez** [comment]
@NeilJ247: I tested using your parameters, and the ú and á characters, with and without the Marshaler, with the SDK and the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html), and I was unable to reproduce the error - the item was created just fine. If you have the CLI installed, would you mind running this command, substituting the appropriate table name and primary key attributes?

`aws dynamodb put-item --debug --table-name "YourTableName" --item '{"YourPrimaryKey": {"S": "SomePrimaryKeyValue"}, "key1": {"S": "Jesús"}, "key2": {"M": {"key3": {"S": "Jesús"}}}}'`

Please let us know whether or not that succeeds, and what the debug output is.

**Comment by NeilJ247** [comment]
Sorry I will look at this ASAP again and get back to you.

**Comment by NeilJ247** [comment]
Hi @howardlopez,

It turns out the issue was on our end. The problem was our MySQL database connection wasn't setting the charset which resulted in reading the non-encoded value and then trying to write/put that value to DynamoDB caused the exception which threw us off a bit.

Thanks for looking into this.
