### ISSUE TITLE
PHP Fatal error Unexpected instance profile response code

### ISSUE THREAD

**Issue by seme1** [aws/aws-sdk-php#1611]
I'm using AWS SDK sessions handler for storing sessions in DynamoDB. I've recently upgraded php version to to 7.1 and noticed in the Apache server log some random warning/fatal errors appearing. I was unable to replicate the issues myself as the sessions seem to be preserved and everything seems to work just fine. Any idea what could be causing the messages shown below ?

It's running on EC2 instance with latest AWS AMI supporting php 7.1 

 ```
[Tue Aug 21 17:41:14.479214 2018] [php7:warn] [pid 12594] [client 172.31.xx.xxx:39574] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.482029 2018] [php7:error] [pid 12594] [client 172.31.xx.xxx:39574] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.667404 2018] [php7:warn] [pid 12563] [client 172.31.xx.xxx:39582] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.667473 2018] [php7:error] [pid 12563] [client 172.31.xx.xxx:39582] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.668069 2018] [php7:warn] [pid 12593] [client 172.31.xx.xxx:39522] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.668111 2018] [php7:error] [pid 12593] [client 172.31.xx.xxx:39522] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.668792 2018] [php7:warn] [pid 12618] [client 172.31.xx.xxx:39536] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.668834 2018] [php7:error] [pid 12618] [client 172.31.xx.xxx:39536] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.669111 2018] [php7:warn] [pid 11316] [client 172.31.xx.xxx:39554] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.669164 2018] [php7:error] [pid 11316] [client 172.31.xx.xxx:39554] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.676515 2018] [php7:warn] [pid 11665] [client 172.31.xx.xxx:39590] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.676559 2018] [php7:error] [pid 11665] [client 172.31.xx.xxx:39590] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.680752 2018] [php7:warn] [pid 12695] [client qqq.qq.qq.qq:9920] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.680794 2018] [php7:error] [pid 12695] [client qqq.qq.qq.qq:9920] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 17:41:14.912264 2018] [php7:warn] [pid 11835] [client 172.31.xx.xxx:39592] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 17:41:14.912395 2018] [php7:error] [pid 11835] [client 172.31.xx.xxx:39592] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code:  in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:96\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult('{\\n  "Code" : "S...')\n#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/functions.php(489): Generator->send('{\\n  "Code" : "S...')\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}('{\\n  "Code" : "S...')\n#4 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, '{\\n  "Code" : "S...', Array)\n#5 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Pr in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 96
[Tue Aug 21 23:27:26.252461 2018] [php7:warn] [pid 13400] [client 172.31.xx.xxx:4336] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 23:27:26.252879 2018] [php7:error] [pid 13400] [client 172.31.xx.xxx:4336] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)) in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:79\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}(Object(GuzzleHttp\\Exception\\ConnectException))\n#1 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(2, Array, Array)\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\\Promise\\TaskQueue->run()\n#4 /var/app/cur in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 79
[Tue Aug 21 23:27:26.596195 2018] [php7:warn] [pid 13414] [client 172.31.38.72:60520] PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/app/current/assets/includeSegs/sessionStart.php on line 39
[Tue Aug 21 23:27:26.596253 2018] [php7:error] [pid 13414] [client 172.31.38.72:60520] PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)) in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:79\nStack trace:\n#0 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}(Object(GuzzleHttp\\Exception\\ConnectException))\n#1 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(2, Array, Array)\n#2 /var/app/current/assets/APIs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#3 /var/app/current/assets/APIs/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\\Promise\\TaskQueue->run()\n#4 /var/app/cur in /var/app/current/assets/APIs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 79
```

```
[ec2-user@ip-172-xx-x-xxx APIs_vendor]$ composer.phar info
aws/aws-sdk-php             3.19.2 AWS SDK for PHP - Use Amazon Web Service...
elasticsearch/elasticsearch v2.2.1 PHP Client for Elasticsearch
guzzlehttp/guzzle           6.2.1  Guzzle is a PHP HTTP client library
guzzlehttp/promises         1.2.0  Guzzle promises library
guzzlehttp/psr7             1.3.1  PSR-7 message implementation
guzzlehttp/ringphp          1.1.0  Provides a simple API and specification ...
guzzlehttp/streams          3.0.0  Provides a simple abstraction over strea...
mashape/unirest-php         1.2.1  Unirest PHP
mtdowling/jmespath.php      2.3.0  Declaratively specify how to extract ele...
psr/http-message            1.0.1  Common interface for HTTP messages
psr/log                     1.0.0  Common interface for logging libraries
react/promise               v2.4.1 A lightweight implementation of CommonJS...
sendgrid/sendgrid           2.1.1  This library allows you to quickly and e...
sendgrid/smtpapi            0.0.1  Build SendGrid X-SMTPAPI headers in PHP.
```

```
[ec2-user@ip-172-xx-x-xxx APIs_vendor]$ php -v
PHP 7.1.17 (cli) (built: May 10 2018 17:38:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @seme1. The errors you're seeing appear to stem from two separate issues.

1. `PHP Warning:  session_start(): Failed to read session data`
    This appears to be due to a particularity introduced with PHP 7.1 - the load session must return an empty string instead of null. More information on this topic can be found in various Github issues ([1](https://github.com/M6Web/RedisBundle/issues/42), [2](https://github.com/dominicklee/PHP-MySQL-Sessions/issues/1), [3](https://github.com/composer/packagist/issues/931)) and StackOverflow posts ([1](https://stackoverflow.com/questions/48245296/php-custom-session-handler-problems-php-7-1), [2](https://stackoverflow.com/questions/41540302/failed-to-read-session-data-on-php7-1)), as well as the comment section of the [session_start function](http://php.net/manual/en/function.session-start.php#120589) in the PHP documentation.
2. `PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Unexpected instance profile response code` and `PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))`
    These errors suggest that the EC2 metadata service on your instance is not working as expected. Unfortunately the first error does not make it clear which HTTP response code was returned by the metadata service, however the second error makes it clear the connection was actively refused by the metadata service. 
    
You can check your instance's EC2 metadata service by running cURL against it (e.g. `$ curl http://169.254.169.254/2018-03-28/meta-data/instance-id` should return the instance ID). If you see that your instance frequently runs into problems when interacting with the EC2 metadata service, a good start to troubleshooting this behavior would be to stop the instance and start it again so it gets moved to different hardware. If you continue to see unexpected behavior from the EC2 metadata service after this on your instance you may want to open a [Premium Support case]() under the `EC2 - Linux` service, or post on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30), for further assistance down this avenue.

**Comment by bounlu** [comment]
I am having the same issue. It's totally random.
