### ISSUE TITLE
Operation not found: PhoneNumberValidate

### ISSUE THREAD

**Issue by vitoacme** [aws/aws-sdk-php#1682]
Looks like `phoneNumberValidate` method is not present in the latest PHP SDK.

PHP SDK: `"aws/aws-sdk-php": "^3.80",`

Code:
```
require 'vendor/autoload.php';

$app_id = 'myappid';

$client = new \Aws\Pinpoint\PinpointClient([
    'version' => 'latest',
    'region'  => 'us-west-2',
    'credentials' => [
        'key'    => 'mykey',
        'secret' => 'mysecret',
    ]
]);

$result = $client->phoneNumberValidate([
    'NumberValidateRequest' => [ // REQUIRED
        'IsoCountryCode' => 'ca',
        'PhoneNumber' => 'canadiannumber',
    ],
]);
```
Stack trace:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Operation not found: PhoneNumberValidate in /vendor/aws/aws-sdk-php/src/AwsClient.php:216
Stack trace:
#0 /vendor/aws/aws-sdk-php/src/AwsClientTrait.php(77): Aws\AwsClient->getCommand('PhoneNumberVali...', Array)
#1 /vendor/aws/aws-sdk-php/src/Pinpoint/PinpointClient.php(160): Aws\AwsClient->__call('phoneNumberVali...', Array)
#2 /playground.php(17): Aws\Pinpoint\PinpointClient->__call('phoneNumberVali...', Array)
#3 {main}
  thrown in /vendor/aws/aws-sdk-php/src/AwsClient.php on line 216
```

**Comment by vitoacme** [comment]
Hi! Not sure how but the SDK probably didn't install properly. When I ran `composer require aws/aws-sdk-php` again, it worked fine. Thank you for you time :)
