### ISSUE TITLE
GuzzleHttp\Promise\RejectionException: Cannot wait on a promise that has no internal wait function

### ISSUE THREAD

**Issue by Capitrium** [aws/aws-sdk-php#1794]
### Version of AWS SDK for PHP?
3.93.5

### Version of PHP (`php -v`)?
PHP 7.2.11-2

### What issue did you see?
Since upgrading to a version including the `ClientSideMonitoring` classes, we've started seeing errors like this when trying to upload files to S3:
```
{
  "exception":"[object] (GuzzleHttp\\Promise\\RejectionException(code: 0): The promise was rejected with reason: Cannot wait on a promise that has no internal wait function. You must provide a wait function when constructing the promise to be able to wait on a promise. at vendor/guzzlehttp/promises/src/functions.php:108)",
  "exception_type":"GuzzleHttp\\Promise\\RejectionException",
  "exception_file":"vendor/guzzlehttp/promises/src/functions.php",
  "exception_line":108,
  "exception_message":"The promise was rejected with reason: Cannot wait on a promise that has no internal wait function. You must provide a wait function when constructing the promise to be able to wait on a promise.",
  "exception_trace":"
    #0 vendor/guzzlehttp/promises/src/RejectedPromise.php(62): GuzzleHttp\\Promise\\exception_for('Cannot wait on a promise that has no internal wait function. You must provide a wait function when constructing the promise to be able to wait on a promise.')
    #1 vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ConfigurationProvider.php(327): wait()
    #2 vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php(271): unwrap(GuzzleHttp\\Promise\\RejectedPromise)
    #3 vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php(176): unwrappedOptions()
    #4 vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php(97): isEnabled()
    #5 vendor/aws/aws-sdk-php/src/ClientResolver.php(609): __invoke(Aws\\Command, GuzzleHttp\\Psr7\\Request)
    #6 vendor/aws/aws-sdk-php/src/Middleware.php(96): Aws\\{closure}(Aws\\Command, GuzzleHttp\\Psr7\\Request)
    #7 vendor/aws/aws-sdk-php/src/Middleware.php(80): Aws\\{closure}(Aws\\Command, NULL)
    #8 vendor/aws/aws-sdk-php/src/S3/S3Client.php(447): Aws\\{closure}(Aws\\Command, NULL)
    #9 vendor/aws/aws-sdk-php/src/S3/S3Client.php(470): Aws\\S3\\{closure}(Aws\\Command, NULL)
    #10 vendor/aws/aws-sdk-php/src/S3/S3Client.php(404): Aws\\S3\\{closure}(Aws\\Command, NULL)
    #11 vendor/aws/aws-sdk-php/src/S3/S3Client.php(423): Aws\\S3\\{closure}(Aws\\Command, NULL)
    #12 vendor/aws/aws-sdk-php/src/Middleware.php(54): Aws\\S3\\{closure}(Aws\\Command, NULL)
    #13 vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\\{closure}(Aws\\Command, NULL)
    #14 vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): __invoke(Aws\\Command, NULL)
    #15 vendor/aws/aws-sdk-php/src/AwsClientTrait.php(64): __invoke(Aws\\Command)
    #16 vendor/aws/aws-sdk-php/src/MultiRegionClient.php(113): executeAsync(Aws\\Command)
    #17 vendor/aws/aws-sdk-php/src/S3/S3MultiRegionClient.php(265): Aws\\{closure}(Aws\\Command)
    #18 [internal function](): Aws\\S3\\{closure}()
    #19 vendor/guzzlehttp/promises/src/functions.php(495): throw(Aws\\S3\\Exception\\PermanentRedirectException)
    #20 vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Promise\\{closure}(Aws\\S3\\Exception\\PermanentRedirectException)
    #21 vendor/guzzlehttp/promises/src/Promise.php(156): callHandler(2, Aws\\S3\\Exception\\PermanentRedirectException, Array)
    #22 vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\\Promise\\{closure}()
    #23 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): run()
    #24 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): tick()
    #25 vendor/guzzlehttp/promises/src/Promise.php(246): execute(true)
    #26 vendor/guzzlehttp/promises/src/Promise.php(223): invokeWaitFn()
    #27 vendor/guzzlehttp/promises/src/Promise.php(266): waitIfPending()
    #28 vendor/guzzlehttp/promises/src/Promise.php(225): invokeWaitList()
    #29 vendor/guzzlehttp/promises/src/Promise.php(269): waitIfPending()
    #30 vendor/guzzlehttp/promises/src/Promise.php(225): invokeWaitList()
    #31 vendor/guzzlehttp/promises/src/Promise.php(62): waitIfPending()
    #32 vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): wait()
    #33 vendor/aws/aws-sdk-php/src/AwsClientTrait.php(77): execute(Aws\\Command)
    #34 application/Services/Logging/S3LogManager.php(77): __call('putObject', Array)
    #35 application/Services/Logging/S3LogManager.php(108): uploadLog('4dfdad4e-aeff-4895-a39b-20034db25ab1', Array)
    #36 application/Workers/MySQLQueueWorker.php(122): flush()
    #37 bin/mysql-worker.php(17): run('4dfdad4e-aeff-4895-a39b-20034db25ab1')
  "
}
```
This did not happen in the release we were using prior to the addition of the `ClientSideMonitoring` classes (`3.64.13`); we've been seeing it sporadically every few weeks since upgrading to `3.72.1`, and we're still seeing it on `3.93.5`.

Why is `ClientSideMonitoring` throwing errors when it should be disabled by default? How do we get rid of these errors?

**Comment by jbmcg** [comment]
I'm also running into this issue. It's very bizarre because it only happens sometimes - it seems like a race condition within the AWS PHP SDK itself. On a batch of 5760 video render jobs today it happened twice - all jobs running on the exact same code / environment / etc.

Here's the code we're using for uploading, it hasn't changed since October 2017:

```
use Aws\CommandPool;

/**
 * @var \Aws\S3\S3Client $s3
 */

$commands = [];
$errors = [];

foreach ($uploads as $fileKey => $path) {
    $commandParams = [
        'Bucket'       => $bucket,
        'Key'          => $fileKey,
        'SourceFile'   => $path,
        'ACL'          => 'public-read',
        'CacheControl' => 'public, max-age=2592000',
    ];
    $extension = pathinfo($path, PATHINFO_EXTENSION);
    if ($extension === 'm3u8') {
        $commandParams['ContentType'] = 'application/vnd.apple.mpegurl';
    }

    $commands[] = $s3->getCommand('putObject', $commandParams);
}

$options = ['concurrency' => 5];
$this->logger->info(
    sprintf('Uploading %d file(s) to S3', count($uploads)),
    $options
);

$pool = new CommandPool($s3, $commands, $options);
$pool->promise()->otherwise(
    function ($e) use (&$errors) {
        $errorMessage = $e->getMessage();
        $this->logger->warning('Error uploading file(s) to S3: ' . $errorMessage);
        $errors[] = $errorMessage;
    }
)->wait();
```

**Comment by howardlopez** [comment]
Thanks for the report! The default behavior for any configuration unpacking issues here should be to disable the module and continue on with the resolution of the request. #1807 has been opened and should take care of this when it is merged.
