### ISSUE TITLE
ApiGatewayManagementApi->deleteConnection

### ISSUE THREAD

**Issue by 4leads** [aws/aws-sdk-php#1904]
### Version of AWS SDK for PHP?
3.118

### Version of PHP (`php -v`)?
7.3

### What issue did you see?
ApiGatewayManagementApi->deleteConnection seems not to be implemented

### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.
call ApiGatewayManagementApi->deleteConnection

### Additional context
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-apigatewaymanagementapi-2018-11-29.html#deleteconnection

**Comment by diehlaws** [comment]
Hi @4leads, thanks for reaching out to us about this. Can you provide a code snippet showing how you are initializing your `ApiGatewayManagementApiClient` and how you are calling `deleteConnection`? What is the exact error returned by the SDK when you try to issue this command?

**Comment by 4leads** [comment]
Sure:

Here Some Pseudocode:

```
class Websocket
{
    static $client;

     /**
     * @return ApiGatewayManagementApiClient
     */
    public static function getClient()
    {
        if (self::$client instanceof ApiGatewayManagementApiClient) {
            return self::$client;
        }
        self::$client = new ApiGatewayManagementApiClient([
            'endpoint' => env('WEBSOCKET_URL'),
            'version' => 'latest',
            'region' => 'eu-central-1',
            'credentials' => [
                'key' => AWS_KEY,
                'secret' => AWS_SECRET,
            ],
        ]);
        return self::$client;
    }

    public static function closeAllConnections($userId)
    {
        $client = self::getClient();
        $connectionIds = self::getConnectionIds($userId);
       
        if ($connectionIds) {
            foreach ($connectionIds as $connectionId) {
             
                try {
                    $client->deleteConnection([
                        'ConnectionId' => $connectionId, // REQUIRED
                    ]);
                } catch (ApiGatewayManagementApiException $e) {

                } 
            }
        }

    }
}
```

and Here the error trace:
Fatal error:  Uncaught InvalidArgumentException: Operation not found: DeleteConnection in path/to/my/app/vendor/aws/aws-sdk-php/src/AwsClient.php:239
Stack trace:
#0 path/to/my/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient-&gt;getCommand('DeleteConnectio...', Array)
#1 path/to/my/app/app/framework/socket/Websocket.php(172): Aws\AwsClient-&gt;__call('deleteConnectio...', Array)
#2 path/to/my/app/app/controller/home/LogoutController.php(25): framework\socket\Websocket::closeAllConnections(1)
#3 path/to/my/app/app/controller/ModernController.php(23): controller\home\LogoutController-&gt;actionIndex()
#4 path/to/my/app/app/framework/Controller.php(66): controller\ModernController-&gt;run()
#5 path/to/my/app/app/framework/Controller.php(38): framework\Controller-&gt;_do_init(Object(stdClass), true, NULL)
#6 /var/w in <b>path/to/my/app/vendor/aws/aws-sdk-php/src/AwsClient.php</b> on line 239

Not sending Messages with the api on the same connectionId works fine.

**Comment by stobrien89** [comment]
Hi @4leads,

Apologies for the delay— were you able to resolve this?  If not, I'd double-check the version you're using, as this operation should be available in version >= `3.110.7`.  `DeleteConnection` was added to the `apigatewaymanagementapi` models on 8/20/2019.  Let us know either way!

**Comment by stobrien89** [comment]
Hi @4leads, 

Closing this for now, but more than happy to re-open if this is still an issue.
