### ISSUE TITLE
Invalid Signature in WriteGetObjectResponse

### ISSUE THREAD

**Issue by petrabarus** [aws/aws-sdk-php#2228]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I tried using the new WriteGetObjectResponse using PHP SDK. It returns below error message

```text
Invoke Error	
{
    "errorType": "Aws\\S3\\Exception\\S3Exception",
    "errorMessage": "Error executing \"WriteGetObjectResponse\" on \"https://io-cell001.s3-object-lambda.ap-southeast-1.amazonaws.com/WriteGetObjectResponse\"; AWS HTTP error: Client error: `POST https://io-cell001.s3-object-lambda.ap-southeast-1.amazonaws.com/WriteGetObjectResponse` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error xmlns=\"\"><Code>InvalidSignature</Code><Message>Invalid signature.</Message> (truncated...)\n  (client):  - <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error xmlns=\"\"><Code>InvalidSignature</Code><Message>Invalid signature.</Message><RequestId>9fe6da15-xxxx-4bff-bef5-xxxxxxxx</RequestId><HostId>{host-id}</HostId></Error>",
    "stack": [
        "#0 /var/task/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\\WrappedHttpHandler->parseError()",
        "#1 /var/task/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\\WrappedHttpHandler->Aws\\{closure}()",
        "#2 /var/task/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler()",
        "#3 /var/task/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()",
        "#4 /var/task/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()",
        "#5 /var/task/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\\Promise\\TaskQueue->run()",
        "#6 /var/task/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\\Handler\\CurlMultiHandler->tick()",
        "#7 /var/task/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute()",
        "#8 /var/task/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()",
        "#9 /var/task/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#10 /var/task/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
        "#11 /var/task/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#12 /var/task/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()",
        "#13 /var/task/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()",
        "#14 /var/task/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()",
        "#15 /var/task/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\\AwsClient->execute()",
        "#16 /var/task/src/index.php(24): Aws\\AwsClient->__call()",
        "#17 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(110): Bref\\Runtime\\FileHandlerLocator->{closure}()",
        "#18 /opt/bref/bootstrap.php(35): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#19 {main}"
    ]
}
```

**Version of AWS SDK for PHP?**
aws/aws-sdk-php                  3.178.0 AWS SDK for PHP - Use Amazon Web Services in your PHP...

**Version of PHP (`php -v`)?**
PHP 7.2.24 (cli)

**To Reproduce (observed behavior)**
I created a repo to reproduce
https://github.com/petrabarus/s3-object-lambda-debug

**Expected behavior**
The S3 API get for S3 Lambda Object should return modified object.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @petrabarus,

Apologies for the delayed response.  Are you still experiencing issues with this? If so, please provide sample code from your script as well as debug logs.  Thanks!

**Comment by petrabarus** [comment]
@stobrien89 I posted this issue when I still worked at AWS last year. It seems like the issue was resolved through internal Slack communication. You can try the sample code here and update the SDK to make sure, anyway.

https://github.com/petrabarus/s3-object-lambda-debug
