### ISSUE TITLE
Copy file with an accesspoint arn does not work

### ISSUE THREAD

**Issue by sascha-mummert** [aws/aws-sdk-php#2299]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution

**Describe the bug**

I used an ARN to an access point to copy a file within an S3 bucket and this did not work.
It rises the error message "Invalid copy source bucket name".

AWS SDK version: 3.178.1 and 3.191.4
PHP version: 7.4.19

**To Reproduce (observed behavior)**
The following code rises the following exception:
```
Aws\S3\Exception\S3Exception - Exception: Error executing "CopyObject" on "https://YOUR_ACCESS_POINT_NAME-YOUR_ACCOUNT_ID.s3-accesspoint.eu-central-1.amazonaws.com/testDestination/testFile.txt"; AWS HTTP error: Client error: `PUT https://YOUR_ACCESS_POINT_NAME-YOUR_ACCOUNT_ID.s3-accesspoint.eu-central-1.amazonaws.com/testDestination/testFile.txt` resulted in a `400 Bad Request` response:
<Error><Code>InvalidArgument</Code><Message>Invalid copy source bucket name</Message><ArgumentName>x-amz-copy-source</Ar (truncated...)
 InvalidArgument (client): Invalid copy source bucket name - <Error><Code>InvalidArgument</Code><Message>Invalid copy source bucket name</Message><ArgumentName>x-amz-copy-source</ArgumentName><ArgumentValue>/arn:aws:s3:eu-central-1:YOUR_ACCOUNT_ID:accesspoint/YOUR_ACCESS_POINT_NAME/testSource%2FtestFile.txt</ArgumentValue><RequestId>AET833EM26XD5Y3D</RequestId><HostId>Es0IO2drWlYr6Q4qp9GvCviSX2zgwga71qWha3wBV/F7k7G9vBeKGRMzWzUcROYgPfmWEJbaEeU=</HostId></Error> 
in /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php (195)

Trace: 
#0 /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler(2, Array, NULL)
#3 /var/www/html/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run()
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /var/www/html/vendor/guzzlehttp/promises/src/Coroutine.php(67): GuzzleHttp\Promise\Promise->wait()
#15 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true)
#16 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#17 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#18 /var/www/html/vendor/guzzlehttp/promises/src/Coroutine.php(103): GuzzleHttp\Promise\Promise->wait(true)
#19 /var/www/html/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(63): GuzzleHttp\Promise\Coroutine->wait()
#20 /var/www/html/src/Test/Test.php(54): Aws\S3\S3Client->copy('arn:aws:s3:eu-c...', 'testSource/test...', 'arn:aws:s3:eu-c...', 'testDestination...')
```

```php
$accessPointArn = 'arn:aws:s3:eu-central-1:YOUR_ACCOUNT_ID:accesspoint/YOUR_ACCESSPOINT_NAME';

$client = new S3Client([
    'credentials' => [
        'key' => 'YOUR_KEY',
        'secret' => 'YOUR_SECRET',
    ],
    'region' => 'eu-central-1',
    'version' => '2006-03-01',
]);

$client->upload($accessPointArn, "testSource/testFile.txt", 'test');

$client->copy(
    $accessPointArn,
    'testSource/testFile.txt',
    $accessPointArn,
    'testDestination/testFile.txt'
);
```

**A hint to the problem**

In the function "\Aws\S3\ObjectCopier::getSourcePath" exists no special handling for the source path if an access point 
ARN will be used.
But the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html) (search for "x-amz-copy-source") 
says there have to be the string "/object/" between the ARN and the key

**Comment by yenfryherrerafeliz** [comment]
This issue has been fixed by the following [PR](https://github.com/aws/aws-sdk-php/pull/2448).

Thanks!
