### ISSUE TITLE
Undefined constant GuzzleHttp\Client::VERSION

### ISSUE THREAD

**Issue by SteveMullen** [aws/aws-sdk-php#2436]
### Describe the bug

PHP Fatal Error

This just started happening today.  Nothing (that I know of) had changed.  I did upgrade from aws.3.198.2 to aws.3.220.3 AFTER the problem began, hoping that would resolve it.  But it did not.

```
[25-Apr-2022 14:37:28 UTC] PHP Fatal error:  Uncaught Error: Undefined constant GuzzleHttp\Client::VERSION in phar:///home/hidden/aws/phar/aws.3.220.3.phar/GuzzleHttp/functions.php:136
Stack trace:
#0 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/Handler/GuzzleV6/GuzzleHandler.php(40): GuzzleHttp\default_user_agent()
#1 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/WrappedHttpHandler.php(87): Aws\Handler\GuzzleV6\GuzzleHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#2 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php(126): Aws\WrappedHttpHandler->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#3 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/S3/PermanentRedirectMiddleware.php(43): Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#4 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/S3/PutObjectUrlMiddleware.php(41): Aws\S3\PermanentRedirectMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#5 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/Middleware.php(126): Aws\S3\PutObjectUrlMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#6 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/FulfilledPromise.php(41): Aws\Middleware::Aws\{closure}(Object(Aws\Credentials\Credentials))
#7 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#8 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#9 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#10 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 /home/hidden/public_vendor/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#13 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#14 phar:///home/hidden/aws/phar/aws.3.220.3.phar/Aws/AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command))
#15 /home/hidden/public_rets/__classes/_roverS3.php(652): Aws\AwsClient->__call('listObjects', Array)
```

### Expected Behavior

Correctly get a list of files from an S3 service

### Current Behavior

PHP Fatal Error

### Reproduction Steps

All S3 operations seem to fail.

### Possible Solution

Some forums suggest GuzzleHttp\Client::VERSION is no longer supported, but the call stack makes it look like the GuzzleHttp\Client::VERSION reference is in `aws/phar/aws.3.220.3.phar/GuzzleHttp/functions.php`

### Additional Information/Context

guzzlehttp/guzzle             7.4.2 

### SDK version used

aws.3.220.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.18

**Comment by SteveMullen** [comment]
I got this working by installing the AWS api via composer, and no longer using the straight php api.  I would still recommend this be looked at - for folks using the php api and also have Guzzle installed via Composer.
