### ISSUE TITLE
CognitoIdentityProviderException not found in WrappedHttpHandler.php

### ISSUE THREAD

**Issue by jaimeburnap** [aws/aws-sdk-php#2508]
### Describe the bug

Running some cognito stuff and something is wrong in terms of the data I'm sending. I would expect to get an error back that I can catch. Instead WrappedHttpHandler tries to instantiate a class PHP thinks doesn't exist. I am calling `adminCreateUser`.

```
PHP Fatal error:  Uncaught Error: Class 'Aws\CognitoIdentityProvider\Exception\CognitoIdentityProviderException' not found in /home/jaime/projects/etl/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
Stack trace:
#0 /home/jaime/projects/etl/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /home/jaime/projects/etl/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /home/jaime/projects/etl/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler(2, Array, NULL)
#3 /home/jaime/projects/etl/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /home/jaime/projects/etl/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /home/jaime/projects/etl/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158) in /home/jaime/projects/etl/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
```

### Expected Behavior

Get a catchable error back.

### Current Behavior

PHP Fatal Error

### Reproduction Steps

```
$client = new CognitoIdentityProviderClient([
	'profile' => '******',
	'region' => 'us-west-2',
	'version' => '2016-04-18'
]);

try {
	$client->adminCreateUser([
		'UserPoolId' => 'us-west-2_*********',
		'MessageAction' => 'SUPPRESS',
		'UserAttributes' => [
			[
				'Name' => 'email_verified',
				'Value' => 'True',
			],
			[
				'Name'=> 'email',
				'Value' => '*****@*****.**',
			],
		'Username' => '*****@*****.**',
	]);
} catch (\Exception $e) {
	echo "$e\n";
}
```

### SDK version used

3.233.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.3.31, Debian GNU/Linux 10

**Comment by yenfryherrerafeliz** [comment]
Hi @jaimeburnap, thanks for opening this issue. I tried to reproduce the reported behavior but I was not able to. The class that the error is complaining about should be auto-loaded by composer. However, could you please enable debug logs. You can do that when instancing the client as follow:
```php
$client = new CognitoIdentityProviderClient([
	'profile' => '******',
	'region' => 'us-west-2',
	'version' => '2016-04-18',
	'debug' => true
]);
```

Could you please also try running ```composer update```? to make sure everything is up to date.

Thanks!

**Comment by stobrien89** [comment]
Hi @jaimeburnap,

Closing this for now.  Let us know if you're still having issues!
