### ISSUE TITLE
S3MultiRegionClient - Wrong region detected when executed from ECS task

### ISSUE THREAD

**Issue by italo1983** [aws/aws-sdk-php#2646]
### Describe the bug

When a S3MultiRegionClient client is instantiated without specifying the region the SDK automatically detects the closest region, in my case eu-central-1 or us-west-2, if the code is run locally and tested via VPN.

When the code is deployed on ECS the client always detects the region where the cluster resides.

`new S3MultiRegionClient([
            'version' => 'latest',
            'signature_version' => 'v4',
            'endpoint' => "https://xxx.mrap.accesspoint.s3-global.amazonaws.com",
            'credentials' => [
                'key'    => 'aws_key',
                'secret' => 'aws_secret'
            ]
          ]);`

### Expected Behavior

The client should return the region closest to the user, analyzing the X-Forwarded-For header and not the host's ip.

### Current Behavior

The client returns the region based on the ip of the Ec2 instance causing the following error if I connect from an IP in Japan but the ECS Cluster is in the Frankfurt region:

Authorization Query Parameters Error
Error parsing the X-Amz-Credential parameter; the region 'eu-central-1' is wrong; expecting 'ap-northeast-1'

### Reproduction Steps

```
$this->s3MultiRegion = new S3MultiRegionClient([
            'version' => 'latest',
            'signature_version' => 'v4',
            'endpoint' => "https://xxx.mrap.accesspoint.s3-global.amazonaws.com",
            'credentials' => [
                'key'    => $this->config->item('aws_key'),
                'secret' => $this->config->item('aws_secret')
            ]
          ]);

$cmd = $this->s3MultiRegion->getCommand('GetObject', [
                                    'Bucket' => $this->bucket_multi,
                                    'Key' => $key
                                ]);

                                $request = $this->s3MultiRegion->createPresignedRequest($cmd, '+1 hour',[
                                  'ReplicationStatus' => 'COMPLETED',
                                ]);
                                $presignedUrl = (string)$request->getUri();
```

### SDK version used

3.260.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4 - Docker with Ubuntu:jammy - Nginx

**Comment by stobrien89** [comment]
Hi @italo1983,

Sorry to hear about the issues.  

As far as I know, we do not use a host IP for determining which region to make a request to/for. Rather, the bucket/access point region is determined by a `HeadBucket` call made from `getBucketRegionAsync` in `S3ClientTrait`.  

It would help to see the resulting endpoint and debug logs for the problematic call (set `'debug' => true` on the client when you generate the endpoint).  If you could provide both  (with any sensitive information redacted) in a response, that would be great.

For what it's worth, I'd recommend dropping the `signature` and `endpoint` configuration options since multi-region access points require sigv4a signing anyway and the correct endpoint will be calculated if you simply pass the multi-region access point arn as the `Bucket` for your command.

**Comment by italo1983** [comment]
Hi @stobrien89 ,
I've modified the Client as you suggested:

```
$this->s3MultiRegion = new S3MultiRegionClient([
            'version' => 'latest',
            'debug' => true,
            'credentials' => [
                'key'    => $this->config->item('aws_key'),
                'secret' => $this->config->item('aws_secret')
            ]
 ]);
```

This is the debug info:

```
-> Entering step init, name 'idempotency_auto_fill'
---------------------------------------------------

  command was set to array(3) {
    ["instance"]=>
    string(32) "0000000034aaad9900000000414a9900"
    ["name"]=>
    string(10) "HeadBucket"
    ["params"]=>
    array(3) {
      ["Bucket"]=>
      string(55) "arn:aws:s3::xxx"
      ["@http"]=>
      array(1) {
        ["debug"]=>
        resource(45) of type (stream)
      }
      ["@context"]=>
      array(0) {
      }
    }
  }
  
  request was set to array(0) {
  }
  


-> Entering step init, name 's3.ssec'
-------------------------------------

  no changes


-> Entering step init, name 's3.source_file'
--------------------------------------------

  no changes


-> Entering step init, name 's3.save_as'
----------------------------------------

  no changes


-> Entering step init, name 's3.location'
-----------------------------------------

  no changes


-> Entering step init, name 's3.auto_encode'
--------------------------------------------

  no changes


-> Entering step init, name 's3.head_object'
--------------------------------------------

  no changes


-> Entering step validate, name 'validation'
--------------------------------------------

  no changes


-> Entering step validate, name 'input_validation_middleware'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'builderV2'
----------------------------------------

  request.instance was set to 0000000034aaac0400000000414a9900
  request.method was set to HEAD
  request.headers was set to array(2) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(54) "xxx.mrap.accesspoint.s3-global.amazonaws.com"
    }
  }
  
  request.scheme was set to https
  request.path was set to /


-> Entering step build, name 's3.check_empty_path_with_query'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'ApiCallMonitoringMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name ''
-------------------------------

  request.instance changed from 0000000034aaac0400000000414a9900 to 0000000034aaac0d00000000414a9900
  request.headers.X-Amz-User-Agent was set to array(1) {
    [0]=>
    string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
  }
  
  request.headers.User-Agent was set to array(1) {
    [0]=>
    string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
  }
  


-> Entering step build, name 'endpoint_parameter'
-------------------------------------------------

  no changes


-> Entering step build, name 'EndpointDiscoveryMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name 'recursion-detection'
--------------------------------------------------

  no changes


-> Entering step build, name 's3.checksum'
------------------------------------------

  no changes


-> Entering step build, name 's3.content_type'
----------------------------------------------

  no changes


-> Entering step build, name 's3.bucket_endpoint_arn'
-----------------------------------------------------

  no changes


-> Entering step sign, name 'StreamRequestPayloadMiddleware'
------------------------------------------------------------

  no changes


-> Entering step sign, name 'invocation-id'
-------------------------------------------

  request.instance changed from 0000000034aaac0d00000000414a9900 to 0000000034aaac0700000000414a9900
  request.headers.aws-sdk-invocation-id was set to array(1) {
    [0]=>
    string(32) "6e7127b4f9540df0292ccb112a9c43bf"
  }
  


-> Entering step sign, name 'retry'
-----------------------------------

  request.instance changed from 0000000034aaac0700000000414a9900 to 0000000034aaac0b00000000414a9900
  request.headers.aws-sdk-retry was set to array(1) {
    [0]=>
    string(3) "0/0"
  }
  


-> Entering step sign, name 's3.put_object_url'
-----------------------------------------------

  no changes


-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

*   Trying 13.248.226.196:443...
* Connected to mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com (13.248.226.196) port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com
*  start date: Jan 10 00:00:00 2023 GMT
*  expire date: Feb  8 23:59:59 2024 GMT
*  subjectAltName: host "mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com" matched cert's "mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
Host: mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com
X-Amz-User-Agent: aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2
aws-sdk-invocation-id: 6e7127b4f9540df0292ccb112a9c43bf
aws-sdk-retry: 0/0
User-Agent: aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2 GuzzleHttp/6.5.5 curl/7.81.0 PHP/7.4.33

* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< x-amz-bucket-region: eu-central-1
< x-amz-request-id: H14ST5FXA6CZPR9Q
< x-amz-id-2: n3ocMPCculN6i8golcUG3EzmHh+axShXhHKOUbtBax2pM4vPbmdQjMKfke9QvyvnUPh/Jd9u7MA=
< Content-Type: application/xml
< Date: Tue, 28 Feb 2023 07:59:54 GMT
< Server: AmazonS3
< Connection: close
< 
* Closing connection 0

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
------------------------------------------------------------------

  error was set to array(13) {
    ["instance"]=>
    string(32) "0000000034aaac1c00000000414a9900"
    ["class"]=>
    string(28) "Aws\S3\Exception\S3Exception"
    ["message"]=>
    string(301) "Error executing "HeadBucket" on "https://mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com/"; AWS HTTP error: Client error: `HEAD https://mxqfea6ficd9g.mrap.accesspoint.s3-global.amazonaws.com/` resulted in a `400 Bad Request` response  (client): 400 Bad Request (Request-ID: H14ST5FXA6CZPR9Q) - "
    ["file"]=>
    string(54) "/app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php"
    ["line"]=>
    int(195)
    ["trace"]=>
    string(1833) "#0 /app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError()
  #1 /app/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}()
  #2 /app/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler()
  #3 /app/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
  #4 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
  #5 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run()
  #6 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick()
  #7 /app/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
  #8 /app/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
  #9 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
  #10 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
  #11 /app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
  #12 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(213): GuzzleHttp\Promise\Promise->wait()
  #13 /app/vendor/aws/aws-sdk-php/src/S3/S3MultiRegionClient.php(316): Aws\S3\S3MultiRegionClient->determineBucketRegion()
  #14 /app/application/controllers/api/Installer.php(656): Aws\S3\S3MultiRegionClient->createPresignedRequest()
  #15 /app/application/libraries/REST_Controller.php(794): Installer->downloadtest_post()
  #16 /app/system/core/CodeIgniter.php(532): REST_Controller->_remap()
  #17 /app/index.php(347): require_once('/app/system/cor...')
  #18 {main}"
    ["type"]=>
    string(6) "client"
    ["code"]=>
    NULL
    ["requestId"]=>
    string(16) "H14ST5FXA6CZPR9Q"
    ["statusCode"]=>
    int(400)
    ["result"]=>
    NULL
    ["request"]=>
    array(5) {
      ["instance"]=>
      string(32) "0000000034aaac0b00000000414a9900"
      ["method"]=>
      string(4) "HEAD"
      ["headers"]=>
      array(6) {
        ["X-Amz-Security-Token"]=>
        string(7) "[TOKEN]"
        ["Host"]=>
        array(1) {
          [0]=>
          string(54) "xxx.mrap.accesspoint.s3-global.amazonaws.com"
        }
        ["X-Amz-User-Agent"]=>
        array(1) {
          [0]=>
          string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
        }
        ["User-Agent"]=>
        array(1) {
          [0]=>
          string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
        }
        ["aws-sdk-invocation-id"]=>
        array(1) {
          [0]=>
          string(32) "6e7127b4f9540df0292ccb112a9c43bf"
        }
        ["aws-sdk-retry"]=>
        array(1) {
          [0]=>
          string(3) "0/0"
        }
      }
      ["scheme"]=>
      string(5) "https"
      ["path"]=>
      string(1) "/"
    }
    ["response"]=>
    array(4) {
      ["instance"]=>
      string(32) "0000000034aaac7400000000414a9900"
      ["statusCode"]=>
      int(400)
      ["headers"]=>
      array(8) {
        ["X-Amz-Security-Token"]=>
        string(7) "[TOKEN]"
        ["x-amz-bucket-region"]=>
        array(1) {
          [0]=>
          string(12) "eu-central-1"
        }
        ["x-amz-request-id"]=>
        array(1) {
          [0]=>
          string(16) "H14ST5FXA6CZPR9Q"
        }
        ["x-amz-id-2"]=>
        array(1) {
          [0]=>
          string(76) "n3ocMPCculN6i8golcUG3EzmHh+axShXhHKOUbtBax2pM4vPbmdQjMKfke9QvyvnUPh/Jd9u7MA="
        }
        ["Content-Type"]=>
        array(1) {
          [0]=>
          string(15) "application/xml"
        }
        ["Date"]=>
        array(1) {
          [0]=>
          string(29) "Tue, 28 Feb 2023 07:59:54 GMT"
        }
        ["Server"]=>
        array(1) {
          [0]=>
          string(8) "AmazonS3"
        }
        ["Connection"]=>
        array(1) {
          [0]=>
          string(5) "close"
        }
      }
      ["body"]=>
      string(0) ""
    }
  }
  
  Inclusive step time: 0.14307618141174


<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.14315915107727


<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.14324498176575


<- Leaving step sign, name 'invocation-id'
------------------------------------------

  no changes
  Inclusive step time: 0.14334988594055


<- Leaving step sign, name 'StreamRequestPayloadMiddleware'
-----------------------------------------------------------

  no changes
  Inclusive step time: 0.14341807365417


<- Leaving step build, name 's3.bucket_endpoint_arn'
----------------------------------------------------

  no changes
  Inclusive step time: 0.14349102973938


<- Leaving step build, name 's3.content_type'
---------------------------------------------

  no changes
  Inclusive step time: 0.14384388923645


<- Leaving step build, name 's3.checksum'
-----------------------------------------

  no changes
  Inclusive step time: 0.14388990402222


<- Leaving step build, name 'recursion-detection'
-------------------------------------------------

  no changes
  Inclusive step time: 0.14394688606262


<- Leaving step build, name 'EndpointDiscoveryMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.14399099349976


<- Leaving step build, name 'endpoint_parameter'
------------------------------------------------

  no changes
  Inclusive step time: 0.14404392242432


<- Leaving step build, name ''
------------------------------

  no changes
  Inclusive step time: 0.14412498474121


<- Leaving step build, name 'ApiCallMonitoringMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.14424395561218


<- Leaving step build, name 's3.check_empty_path_with_query'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.1444981098175


<- Leaving step build, name 'builderV2'
---------------------------------------

  no changes
  Inclusive step time: 0.14472079277039


<- Leaving step validate, name 'input_validation_middleware'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.14619588851929


<- Leaving step validate, name 'validation'
-------------------------------------------

  no changes
  Inclusive step time: 0.14624500274658


<- Leaving step init, name 's3.head_object'
-------------------------------------------

  no changes
  Inclusive step time: 0.14632201194763


<- Leaving step init, name 's3.auto_encode'
-------------------------------------------

  no changes
  Inclusive step time: 0.14635610580444


<- Leaving step init, name 's3.location'
----------------------------------------

  no changes
  Inclusive step time: 0.14639687538147


<- Leaving step init, name 's3.save_as'
---------------------------------------

  no changes
  Inclusive step time: 0.14643311500549


<- Leaving step init, name 's3.source_file'
-------------------------------------------

  no changes
  Inclusive step time: 0.14647912979126


<- Leaving step init, name 's3.ssec'
------------------------------------

  no changes
  Inclusive step time: 0.14654207229614


<- Leaving step init, name 'idempotency_auto_fill'
--------------------------------------------------

  no changes
  Inclusive step time: 0.14685702323914


-> Entering step init, name 'idempotency_auto_fill'
---------------------------------------------------

  command was set to array(3) {
    ["instance"]=>
    string(32) "0000000034aaac4e00000000414a9900"
    ["name"]=>
    string(9) "GetObject"
    ["params"]=>
    array(4) {
      ["Bucket"]=>
      string(55) "arn:aws:s3::xxx:accesspoint/xxx.mrap"
      ["Key"]=>
      string(79) "filename.dmg"
      ["@http"]=>
      array(1) {
        ["debug"]=>
        resource(65) of type (stream)
      }
      ["@context"]=>
      array(0) {
      }
    }
  }
  
  request was set to array(0) {
  }
  


-> Entering step init, name 's3.ssec'
-------------------------------------

  no changes


-> Entering step init, name 's3.source_file'
--------------------------------------------

  no changes


-> Entering step init, name 's3.save_as'
----------------------------------------

  no changes


-> Entering step init, name 's3.location'
-----------------------------------------

  no changes


-> Entering step init, name 's3.auto_encode'
--------------------------------------------

  no changes


-> Entering step init, name 's3.head_object'
--------------------------------------------

  no changes


-> Entering step validate, name 'validation'
--------------------------------------------

  no changes


-> Entering step validate, name 'input_validation_middleware'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'builderV2'
----------------------------------------

  request.instance was set to 0000000034aaacb100000000414a9900
  request.method was set to GET
  request.headers was set to array(2) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(54) "xxx.mrap.accesspoint.s3-global.amazonaws.com"
    }
  }
  
  request.scheme was set to https
  request.path was set to filename.dmg


-> Entering step build, name 's3.check_empty_path_with_query'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'ApiCallMonitoringMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name ''
-------------------------------

  request.instance changed from 0000000034aaacb100000000414a9900 to 0000000034aaaf4600000000414a9900
  request.headers.X-Amz-User-Agent was set to array(1) {
    [0]=>
    string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
  }
  
  request.headers.User-Agent was set to array(1) {
    [0]=>
    string(86) "aws-sdk-php/3.261.0 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2"
  }
  


-> Entering step build, name 'endpoint_parameter'
-------------------------------------------------

  no changes


-> Entering step build, name 'EndpointDiscoveryMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name 'recursion-detection'
--------------------------------------------------

  no changes


-> Entering step build, name 's3.checksum'
------------------------------------------

  no changes


-> Entering step build, name 's3.content_type'
----------------------------------------------

  no changes


-> Entering step build, name 's3.bucket_endpoint_arn'
-----------------------------------------------------

  no changes


-> Entering step sign, name 'StreamRequestPayloadMiddleware'
------------------------------------------------------------

  no changes


-> Entering step sign, name 'invocation-id'
-------------------------------------------

  request.instance changed from 0000000034aaaf4600000000414a9900 to 0000000034aaacb000000000414a9900
  request.headers.aws-sdk-invocation-id was set to array(1) {
    [0]=>
    string(32) "2cac5a9680e2209af529355a05156905"
  }
  


-> Entering step sign, name 'retry'
-----------------------------------

  request.instance changed from 0000000034aaacb000000000414a9900 to 0000000034aaaf4400000000414a9900
  request.headers.aws-sdk-retry was set to array(1) {
    [0]=>
    string(3) "0/0"
  }
  


-> Entering step sign, name 's3.put_object_url'
-----------------------------------------------

  no changes


-> Entering step sign, name 's3.permanent_redirect'
---------------------------------------------------

  no changes


-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes


<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
------------------------------------------------------------------

  result was set to array(2) {
    ["instance"]=>
    string(32) "0000000034aaaf4500000000414a9900"
    ["data"]=>
    array(0) {
    }
  }
  
  Inclusive step time: 0.00020003318786621


<- Leaving step sign, name 's3.permanent_redirect'
--------------------------------------------------

  no changes
  Inclusive step time: 0.00024199485778809


<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.0002751350402832


<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.00031399726867676


<- Leaving step sign, name 'invocation-id'
------------------------------------------

  result.data.@metadata was set to array(1) {
    ["transferStats"]=>
    array(1) {
      ["http"]=>
      array(1) {
        [0]=>
        array(0) {
        }
      }
    }
  }
  
  Inclusive step time: 0.00040602684020996


<- Leaving step sign, name 'StreamRequestPayloadMiddleware'
-----------------------------------------------------------

  no changes
  Inclusive step time: 0.00045299530029297


<- Leaving step build, name 's3.bucket_endpoint_arn'
----------------------------------------------------

  no changes
  Inclusive step time: 0.0004889965057373


<- Leaving step build, name 's3.content_type'
---------------------------------------------

  no changes
  Inclusive step time: 0.00053000450134277


<- Leaving step build, name 's3.checksum'
-----------------------------------------

  no changes
  Inclusive step time: 0.00055789947509766


<- Leaving step build, name 'recursion-detection'
-------------------------------------------------

  no changes
  Inclusive step time: 0.00059199333190918


<- Leaving step build, name 'EndpointDiscoveryMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.00062108039855957


<- Leaving step build, name 'endpoint_parameter'
------------------------------------------------

  no changes
  Inclusive step time: 0.00065517425537109


<- Leaving step build, name ''
------------------------------

  no changes
  Inclusive step time: 0.00071501731872559


<- Leaving step build, name 'ApiCallMonitoringMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.000762939453125


<- Leaving step build, name 's3.check_empty_path_with_query'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.0009009838104248


<- Leaving step build, name 'builderV2'
---------------------------------------

  no changes
  Inclusive step time: 0.00098586082458496


<- Leaving step validate, name 'input_validation_middleware'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.0012578964233398


<- Leaving step validate, name 'validation'
-------------------------------------------

  no changes
  Inclusive step time: 0.0012929439544678


<- Leaving step init, name 's3.head_object'
-------------------------------------------

  no changes
  Inclusive step time: 0.001366138458252


<- Leaving step init, name 's3.auto_encode'
-------------------------------------------

  no changes
  Inclusive step time: 0.0013880729675293


<- Leaving step init, name 's3.location'
----------------------------------------

  no changes
  Inclusive step time: 0.0014119148254395


<- Leaving step init, name 's3.save_as'
---------------------------------------

  no changes
  Inclusive step time: 0.0014340877532959


<- Leaving step init, name 's3.source_file'
-------------------------------------------

  no changes
  Inclusive step time: 0.0014598369598389


<- Leaving step init, name 's3.ssec'
------------------------------------

  no changes
  Inclusive step time: 0.0014989376068115


<- Leaving step init, name 'idempotency_auto_fill'
--------------------------------------------------

  no changes
  Inclusive step time: 0.0015740394592285
```

**Comment by stobrien89** [comment]
Hi @italo1983,

Thanks for the additional info.  

Do you happen to know which credentials you're using for these calls? The 400 from the HeadBucket call seems to indicate that the credentials you're using don't have permissions to access the mrap.  I'm thinking it's possible you're using EC2 role credentials that may not have the S3 permissions you need.  If that's the case, you might want to fetch a different set of credentials using STS and use them to make these calls.

**Comment by italo1983** [comment]
If i use the S3Client instead of S3MultiClient to generate the presigned URL the problem does not occurr. Need specific permission for mrap?
Il 28 feb 2023, 18:57 +0100, stobrien89 ***@***.***>, ha scritto:

**Comment by italo1983** [comment]
Hi @stobrien89, 
I don't think it's a problem with credentials or configuration.
Calling directly headBucket with same settings I'm getting this:

```
-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes


*   Trying 76.223.97.181:443...
* Connected to xxx.mrap.accesspoint.s3-global.amazonaws.com (76.223.97.181) port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=xxx.mrap.accesspoint.s3-global.amazonaws.com
*  start date: Jan 10 00:00:00 2023 GMT
*  expire date: Feb  8 23:59:59 2024 GMT
*  subjectAltName: host "xxx.mrap.accesspoint.s3-global.amazonaws.com" matched cert's "xxx.mrap.accesspoint.s3-global.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
Host: xxx.mrap.accesspoint.s3-global.amazonaws.com
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
aws-sdk-invocation-id: ffeef775fa93174bfc3f6aea95ebbe18
aws-sdk-retry: 0/0
X-Amz-User-Agent: aws-sdk-php/3.261.1 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2
X-Amz-Date: 20230301T215659Z
X-Amz-Region-Set: *
Authorization: AWS4-ECDSA-P256-SHA256 Credential=[KEY]/20230301/s3/aws4_request, SignedHeaders=host;x-amz-date;x-amz-region-set;x-amz-user-agent, Signature=[SIGNATURE]
User-Agent: aws-sdk-php/3.261.1 OS/Linux/4.14.256-197.484.amzn2.x86_64 lang/php/7.4.33 AWS_ECS_EC2 GuzzleHttp/6.5.5 curl/7.81.0 PHP/7.4.33

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
```
Instead the createPresignedRequest hit a 400 error:
```"Error executing "HeadBucket" on "https://xxx.mrap.accesspoint.s3-global.amazonaws.com/"; AWS HTTP error: Client error: `HEAD https://xxx.mrap.accesspoint.s3-global.amazonaws.com/` resulted in a `400 Bad Request` response  (client): 400 Bad Request (Request-ID: CNEHN477B2MG1ZVM) - "```

I've also compiled and installed the aws-crt-php module but the problem persist.

**Comment by stobrien89** [comment]
Hi @italo1983,

Thanks for your patience.  I did some digging and was able to identify the behavior you're seeing as a bug— we're scoping credentials to a particular region when presigning in both the standard client and multi-region client.  This is obviously problematic for a multi-region resource. 

I'm expecting to have a fix for this by next week, but please let us know if you have any questions in the meantime.

**Comment by italo1983** [comment]
Hi @stobrien89,
thank you very much!

**Comment by italo1983** [comment]
Can you explain to me why it works correctly locally? This thing made me think that the problem was related only to ECS :)

**Comment by stobrien89** [comment]
Hi @italo1983,

It's hard to say without being able to compare with debug logs from your local client code (and knowing which objects you're trying to access, which buckets they reside in, etc.), but at least from what I've observed, I'm getting the same error when I hard-code a region other than the "base" region for the s3 account.  I've compared our SDK behavior to that of the CLI/Python SDK and noticed that we're incorrectly signing these requests.

**Comment by stobrien89** [comment]
Hi @italo1983,

The fix for this should be available in today's release.  Please confirm whether or not this works for you!
