### ISSUE TITLE
Uncaught Error: Call to undefined function GuzzleHttp\default_user_agent()(short issue description)

### ISSUE THREAD

**Issue by faridjc** [aws/aws-sdk-php#2777]
### Describe the bug

I am getting the following error while trying to retrieve objects using the `listObjects` method:
```
PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\default_user_agent() in C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\Handler\GuzzleV6\GuzzleHandler.php:40
```

My code:
```
namespace MyNamespace;

use \Aws\S3\S3Client;
use \Aws\Exception\AwsException;


class MyClass {
       public function myFunction(){
                require_once '/path/to/autoload.php';
	
		$client = new \Aws\S3\S3Client(array(
			'region' => 'us-west-1',
			'credentials' =>  [
				'key'    =>'XXXXXXXXXXXXXXXXXX',
				'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXX',
			],
			
		));
		
		$bucket_name = 'XXXXXXXX';
		
		try {
			$contents = $client->listObjects([
				'Bucket' => $bucket_name,
			]);
			echo "The contents of your bucket are: \n";
			print_r($contents);
		} catch (S3Exception  $exception) {
			echo "Failed to list objects in $bucket_name with error: " . $exception->getMessage();
			exit("Please fix error with listing objects before continuing.");
		}
       }
}
```

### Expected Behavior

Objects in the specified bucket should be printed.

### Current Behavior

A fatal error occurs.

### Reproduction Steps

1) Install aws/aws-sdk-php using composer 
2) Instance class
3) Call MyFunction
4) See fatal error occur

### Possible Solution

Changing the function being called on line 40 to `\GuzzleHttp\Utils::defaultUserAgent()` solves it.

### Additional Information/Context

Stack trace:
```
[13-Sep-2023 19:33:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\default_user_agent() in C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\Handler\GuzzleV6\GuzzleHandler.php:40
Stack trace:
#0 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php(88): Aws\Handler\GuzzleV6\GuzzleHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#1 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\ClientSideMonitoring\AbstractMonitoringMiddleware.php(126): Aws\WrappedHttpHandler->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#2 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\S3\PermanentRedirectMiddleware.php(43): Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#3 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\S3\PutObjectUrlMiddleware.php(41): Aws\S3\PermanentRedirectMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#4 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\Middleware.php(152): Aws\S3\PutObjectUrlMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
#5 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\FulfilledPromise.php(48): Aws\Middleware::Aws\{closure}(Object(Aws\Credentials\Credentials))
#6 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#7 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#8 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#10 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 C:\...\wp-content\plugins\...\vendor\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#12 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#13 C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command))
#14 C:\...\wp-content\plugins\...\log-cleanup\...-log-cleanup.php(36): Aws\AwsClient->__call('listObjects', Array)
#15 C:\...\wp-content\plugins\...\log-cleanup\...-log-cleanup.php(98): wpp_integrations_log_cleanup_execute()
#16 C:\...\wp-includes\rest-api\class-wp-rest-server.php(1188): wpp_integrations_log_cleanup_handle_execute_request(Object(WP_REST_Request))
#17 C:\...\wp-includes\rest-api\class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/log_cleanup/v1...', Array, NULL)
#18 C:\...\wp-includes\rest-api\class-wp-rest-server.php(447): WP_REST_Server->dispatch(Object(WP_REST_Request))
#19 C:\...\wp-includes\rest-api.php(418): WP_REST_Server->serve_request('/log_cleanup/v1...')
#20 C:\...\wp-includes\class-wp-hook.php(310): rest_api_loaded(Object(WP))
#21 C:\...\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#22 C:\...\wp-includes\plugin.php(565): WP_Hook->do_action(Array)
#23 C:\...\wp-includes\class-wp.php(398): do_action_ref_array('parse_request', Array)
#24 C:\...\wp-includes\class-wp.php(779): WP->parse_request('')
#25 C:\...\wp-includes\functions.php(1335): WP->main('')
#26 C:\...\wp-blog-header.php(16): wp()
#27 C:\...\index.php(17): require('C:\\Users\\...')
#28 {main}
  thrown in C:\...\wp-content\plugins\...\vendor\aws\aws-sdk-php\src\Handler\GuzzleV6\GuzzleHandler.php on line 40
```
Environment:

 - Windows 10
 - PHP 7.4.33
 - Composer 2.6.2
 - aws/aws-sdk-php 3.281.6

Things I tried:

 - Changing PHP version to 8+
 - Downgrading to several other aws/aws-sdk-php versions
 - Other  credential methods

### SDK version used

3.281.5

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.33

**Comment by yenfryherrerafeliz** [comment]
Hi @faridjc, this issue tends to happen when using an outdated guzzle version. Could you please try to update your dependencies by deleting composer.lock file and running composer update. You can also try by creating a new project from scratch, which I did and I did not have any issues.

I hope this helps!

Thanks!

**Comment by faridjc** [comment]
Hello @yenfryherrerafeliz, the issue was a conflict with another plugin that also had Guzzle in its source and had an older version. Your response helped me go the right path. I disabled the plugin and the issue is not present anymore.

Thank you!
