### ISSUE TITLE
ObjectUploader fails for files >16mb with Aws\S3\Exception\S3MultipartUploadException

### ISSUE THREAD

**Issue by ocostello** [aws/aws-sdk-php#2929]
### Describe the bug

We'd noticed a lot of this type of error in our production logs so looked in to the files causing the issue and noticed they were all >16mb which is the default cutoff for the method using a multipart upload.
After more testing it seems incredibly consistent, any upload attempt over 16mb using the `ObjectUploader` fails with the following error. I've updated to the most recent SDK version and the issue is still the same. 

**Note:** some other code paths of our app use the `createMultipartUpload` -> `uploadPart` -> `completeMultipartUpload` _instead_ and that works for any file size. 

### Expected Behavior

ObjectUpload should work with files of all sizes and use multipart uploads at the right time

### Current Behavior

```console
Next Aws\S3\Exception\S3Exception: Error executing "CompleteMultipartUpload" on "https://{redacted-bucket-name}.s3.amazonaws.com/{redacted-key}?uploadId={redacted-key}"; AWS HTTP error: Client error: `POST https://{redacted-bucket}.s3.amazonaws.com/{redacted-key}?uploadId={redacted-key}` resulted in a `400 Bad Request` response:
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our publis (truncated...)
 MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>{redacted-key}</RequestId><HostId>{redacted-key}</HostId></Error> in /opt/bipsync/release/development/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:196
Stack trace:
#0 /opt/bipsync/release/development/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError()
#1 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(209): Aws\WrappedHttpHandler->Aws\{closure}()
#2 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler()
#3 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/RejectedPromise.php(49): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /opt/bipsync/release/development/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run()
#6 /opt/bipsync/release/development/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute()
#8 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Coroutine.php(68): GuzzleHttp\Promise\Promise->wait()
#15 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}()
#16 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#17 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#18 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#19 /opt/bipsync/release/development/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#20 /opt/bipsync/release/development/vendor/aws/aws-sdk-php/src/S3/ObjectUploader.php(100): GuzzleHttp\Promise\Promise->wait()
#21 /opt/bipsync/release/development/lib/S3/Storage.php(355): Aws\S3\ObjectUploader->upload()
#22 /opt/bipsync/release/development/importer/class/Importer/Movefiletos3.php(95): S3\Storage->objectUpload()
#23 /opt/bipsync/release/development/lib/Team/Worker.php(137): Importer\Movefiletos3->work()
#24 /opt/bipsync/release/development/lib/Team/Worker.php(103): Team\Worker->loop()
#25 /opt/bipsync/release/development/lib/Team/Router.php(107): Team\Worker->start()
#26 /opt/bipsync/release/development/lib/WebApp/Bootstrap.php(87): Team\Router->run()
#27 /opt/bipsync/release/development/importer/importer.php(6): WebApp\Bootstrap->run()
#28 {main}
```

### Reproduction Steps

Our usage of `ObjectUploader` looks like this

```php
$config = [
   'version' => 'latest',
   'signature' => $options->s3->signature,
   'region' => $options->s3->region
];

$config = array_merge( $config, [
   'credentials' => new Credentials( $options->s3->key, $options->s3->secret )
] );

$client = new S3Client( $config );

$uploader = new ObjectUploader( $client, $options->s3->bucket, $key, $stream, $acl );

$result = $uploader->upload(); 
```

### SDK version used

^3.283 (and tested on 3.308.4)

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3, Linux

**Comment by ocostello** [comment]
I've been off holiday for a week so been unable to reply, apologies. After a few red herrings we realised that somewhere before use of the ObjectUploader we were reading the stream to another temp file (to calculate our own hash of it), like so
```
            file_put_contents( $tempPath, $stream );
```
And when we rewinded the stream _after_ this and _before_ the ObjectUploader usage, everything worked as it should. I'm not sure if the rewind is something the SDK would consider baking in for cases like this; I could see how this could be filed under 'unexpected use'
