### ISSUE TITLE
Missing file Sqs/Exception/Exception.php

### ISSUE THREAD

**Issue by alexzabolotny** [aws/aws-sdk-php#557]
SQS lib does not throw an exception, because the exception class not found:
```
include(/app/vendor/aws/aws-sdk-php/src/Aws/Sqs/Exception/Exception.php): failed to open stream: No such file or directory (/app/vendor/yiisoft/yii/framework/yiilite.php:253) 
Stack trace: 
#0 unknown(0): spl_autoload_call() 
#1 /app/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php(74): class_exists() 
#2 /app/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/ExceptionListener.php(55): Aws\Common\Exception\NamespaceExceptionFactory->fromResponse() 
#3 unknown(0): Aws\Common\Exception\ExceptionListener->onRequestError() 
#4 /app/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func() 
#5 /app/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() 
#6 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() 
#7 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\EntityEnclosingRequest->processResponse() 
#8 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\EntityEnclosingRequest->setState() 
#9 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState() 
#10 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse() 
#11 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages() 
#12 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles() 
#13 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform() 
#14 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send() 
#15 /app/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send() 
#16 /app/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(256): Aws\Sqs\SqsClient->send() 
#17 /app/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Aws\Sqs\SqsClient->send() 
#18 /app/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): Aws\Sqs\SqsClient->execute() 
#19 /app/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(189): Aws\Common\Command\QueryCommand->execute() 
#20 /app/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(76): Aws\Common\Command\QueryCommand->getResult() 
#21 /app/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(104): Aws\Sqs\SqsClient->__call() 
#22 ... 
#23 ... 
#24 /app/vendor/yiisoft/yii/framework/yiilite.php(1070): AmazonSqsComponent->init() 
#25 /app/vendor/yiisoft/yii/framework/yiilite.php(922): WebApplication->getComponent() 
#26 ... 
#27 ... 
#28 ... 
#29 ...
#30 /app/vendor/yiisoft/yii/framework/yiilite.php(3652): CInlineAction->runWithParams() 
#31 /app/vendor/yiisoft/yii/framework/yiilite.php(3637): CallbackController->runAction() 
#32 /app/vendor/yiisoft/yii/framework/yiilite.php(3627): CallbackController->runActionWithFilters() 
#33 /app/vendor/yiisoft/yii/framework/yiilite.php(1761): CallbackController->run() 
#34 ... 
#35 /app/vendor/yiisoft/yii/framework/yiilite.php(1202): WebApplication->processRequest() 
#36 /app/public_html/index.php(66): WebApplication->run() 
```

There are other files that seem to be missing, for example: Sqs/Exception/InternalErrorException.php.

**Comment by mtdowling** [comment]
Is your Yii autoloader not checking if the file exists before attempting to include it? If it is not doing this, then it will not work correctly with the SDK because the autoloader is not allowing other autoloaders to load the class.

**Comment by z-sahil** [comment]
@alexzabolotny did you find any solution for this issue? I'm facing a very similar issue to this while using aws php sdk & yii 1
