### ISSUE TITLE
Php Sdk Phar reporting .pem MD5 mismatch... 

### ISSUE THREAD

**Issue by jozeperez** [aws/aws-sdk-php#800]
As of this morning my application began to fail because of a "/tmp/guzzle-cacert.pem" MD5 mismatch. Here is the error_log info:
```
PHP Fatal error:  Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message '/tmp/guzzle-cacert.pem MD5 mismatch: expected 47961e7ef15667c93cd99be01b51f00a but got 6c81b1339b320190689e4c2d594ca67f' in phar:///aws.phar/Guzzle/Http/Client.php:354
Stack trace:
#0 phar:///aws.phar/Guzzle/Http/Client.php(469): Guzzle\Http\Client->preparePharCacert()
#1 phar:///aws.phar/Guzzle/Http/Client.php(74): Guzzle\Http\Client->initSsl()
#2 phar:///aws.phar/Aws/Common/Client/AbstractClient.php(76): Guzzle\Http\Client->__construct('https://s3.amaz...', Object(Guzzle\Common\Collection))
#3 phar:///aws.phar/Aws/Common/Client/ClientBuilder.php(252): Aws\Common\Client\AbstractClient->__construct(Object(Aws\Common\Credentials\Credentials), Object(Aws\S3\S3Signature), Object(Guzzle\Common\Collection))
#4 phar:///aws.phar/Aws/S3/S3Client.php(254): Aws\Common\Clien in phar:///aws.phar/Guzzle/Http/Client.php on line 354
```
Nothing was changed on the application or the server. I'm also running PHP 5.4.45.

Any ideas?

**Comment by jeskew** [comment]
Could you try deleting the file .pem file in `/tmp` and seeing if that helps?

**Comment by jozeperez** [comment]
That worked! Thanks. Question: Why did this happen?

**Comment by jeskew** [comment]
Looks like it's related to https://github.com/guzzle/guzzle/issues/568.
