### ISSUE TITLE
uploadDirectory() return "Errors during multi transfer" when trying to upload any folder with a file larger than 2GB 

### ISSUE THREAD

**Issue by pihish** [aws/aws-sdk-php#820]
I use the following to upload a directory from my Windows Server 2012 R2 running IIS 8.5 + PHP 5.6 + AWS SDK 2.8:

```try{
    $s3Client->uploadDirectory("c:/temp", S3_PROJECTS_BUCKET, "/temp", array(
        "params" => array(
            "ACL" => "public-read",
            "ContentDisposition" => "attachment"
        ),
        "multipart_upload_size" => 3932160,
        "concurrency" => 10
    ));
}
catch(Exception $e){
    echo $e->getMessage();
}
```

If any file within *c:/temp* is bigger than 2GB, I receive an "Errors during multi transfer" exception along with a trace log.  If all files within the folder are individually smaller than 2GB, there are no problems.  Folders greater than 2GB but where individual files are less than 2GB are fine.  I've uploaded folders whose cumulative sizes are larger than 20GB.

In the above code example, "concurrency" is set at 10 and "multipart_upload_size" at 3MB.  I've played around with multiple values for both of those keys and the results have always been the same.   I've also tried calling the request without the last optional array parameter in "uploadDirectory()" and the same error occurs.  

I've set max file size uploads to 5GB and turned off all timeouts in php.ini.  I've also increased timeouts to large values in IIS.

What am I missing here?

**Comment by jeremeamia** [comment]
You are experiencing the infamous PHP–Windows error: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#why-can-t-i-upload-or-download-files-greater-than-2gb

**Comment by pihish** [comment]
Here's the full exception log:

```
Errors during multi transfer
(Aws\S3\Exception\S3Exception) phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/Common/Exception/NamespaceExceptionFactory.php line 91
  An error occurred when parsing the HTTP request
    #0 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/Common/Exception/NamespaceExceptionFactory.php(76): Aws\Common\Exception\NamespaceExceptionFactory->createException('Aws\\S3\\Exceptio...', Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response), Array)
    #1 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/Common/Exception/ExceptionListener.php(55): Aws\Common\Exception\NamespaceExceptionFactory->fromResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
    #2 [internal function]: Aws\Common\Exception\ExceptionListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #3 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #4 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
    #5 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
    #6 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
    #7 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
    #8 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
    #9 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #10 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
    #11 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
    #12 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
    #13 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
    #14 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Client.php(386): Guzzle\Http\Curl\CurlMultiProxy->send()
    #15 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Http/Client.php(279): Guzzle\Http\Client->sendMultiple(Array)
    #16 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/Common/Client/AbstractClient.php(256): Guzzle\Http\Client->send(Array)
    #17 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Service/Client.php(233): Aws\Common\Client\AbstractClient->send(Array)
    #18 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Guzzle/Service/Client.php(140): Guzzle\Service\Client->executeMultiple(Array)
    #19 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/S3/Sync/AbstractSync.php(118): Guzzle\Service\Client->execute(Array)
    #20 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/S3/Sync/AbstractSync.php(107): Aws\S3\Sync\AbstractSync->transferCommands(Array)
    #21 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/S3/Sync/AbstractSync.php(64): Aws\S3\Sync\AbstractSync->transferFiles(Array)
    #22 phar://C:/inetpub/wwwroot/lib/vendor/aws.phar/Aws/S3/S3Client.php(580): Aws\S3\Sync\AbstractSync->transfer()
    #23 .\temp.php(17): Aws\S3\S3Client->uploadDirectory('c:/temp', 'my-bucket...', '/temp')
    #24 {main}
```

**Comment by pihish** [comment]
Lucky me!!!

**Comment by jeskew** [comment]
On the plus side, PHP 7 will support large files and 64-bit numbers. Unfortunately, only RC releases are available for [download](http://windows.php.net/qa/). A GA release should [be coming out soon](https://wiki.php.net/todo/php70#timetable) (i.e., before December), though!
