### ISSUE TITLE
Error when using paginator with ListResourceRecordSets

### ISSUE THREAD

**Issue by PSiAU** [aws/aws-sdk-php#851]
I'm not sure if this is a bug/unexpected behavior or not, but when using the ListResourceRecordSets paginator for Route53, the SDK lists all the records as expected but then throws an error at the end of the list. It's as if it doesn't realise it's at the end of the list and requests more records.

Example:
```
$result = $route53client->getPaginator('ListResourceRecordSets', [
  'HostedZoneId' => 'xxxxxxxxxx',
]);
foreach ($result->search('ResourceRecordSets[]') as $record) {
  print_r($record);
}
```
It throws this error:
```
PHP Notice:  Undefined offset: 2 in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/ResultPaginator.php on line 151

Notice: Undefined offset: 2 in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/ResultPaginator.php on line 151
PHP Fatal error:  Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the ListResourceRecordSets operation:
[StartRecordIdentifier] must be at least 1 characters long. Value provided is 0 characters long. in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Api/Validator.php:38
Stack trace:
#0 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Middleware.php(77): Aws\Api\Validator->validate('ListResourceRec...', Object(Aws\Api\StructureShape), Array)
#1 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Route53/Route53Client.php(125): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/AwsClient.php(208): Aws\Route53\Route53Client->Aws\Route53\{closure}(Object(Aws\Command))
#3 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/AwsClient.php(202): Aws\AwsClient->executeAsync(Object(Aws\Command))
#4 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/ResultPaginator.php(127): Aws\AwsClient->execute(Object(Aws\Command))
#5 /usr/local/awssdkphp3/ve in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 38

Fatal error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the ListResourceRecordSets operation:
[StartRecordIdentifier] must be at least 1 characters long. Value provided is 0 characters long. in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Api/Validator.php:38
Stack trace:
#0 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Middleware.php(77): Aws\Api\Validator->validate('ListResourceRec...', Object(Aws\Api\StructureShape), Array)
#1 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Route53/Route53Client.php(125): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/AwsClient.php(208): Aws\Route53\Route53Client->Aws\Route53\{closure}(Object(Aws\Command))
#3 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/AwsClient.php(202): Aws\AwsClient->executeAsync(Object(Aws\Command))
#4 /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/ResultPaginator.php(127): Aws\AwsClient->execute(Object(Aws\Command))
#5 /usr/local/awssdkphp3/ve in /usr/local/awssdkphp3/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 38
```

**Comment by jeskew** [comment]
Thanks for reporting this. Did the code provided above just start throwing errors without any changes on your part?

**Comment by PSiAU** [comment]
No i'm using paginators with route53 for the first time, so I can't say if this worked in previous versions.
