### ISSUE TITLE
Error on authentication

### ISSUE THREAD

**Issue by IgorDePaula** [aws/aws-sdk-php#855]
I receive this error with script

```php
<?php

use Aws\Common\Aws;

// Create a service builder using a configuration file
$aws = Aws::factory('/path/to/my_config.json');

// Get the client from the builder by namespace
$client = $aws->get('Sqs');

$result = $client->createQueue(array('QueueName' => 'my-queue'));
$queueUrl = $result->get('QueueUrl');

$result = $client->createQueue(array(
    'QueueName'  => 'my-queue',
    'Attributes' => array(
        'DelaySeconds'       => 5,
        'MaximumMessageSize' => 4096, // 4 KB
    ),
));
$queueUrl = $result->get('QueueUrl');

$client->sendMessage(array(
    'QueueUrl'    => $queueUrl,
    'MessageBody' => 'An awesome message!',
));

$client->sendMessage(array(
    'QueueUrl'     => $queueUrl,
    'MessageBody'  => 'An awesome message!',
    'DelaySeconds' => 30,
));

$result = $client->receiveMessage(array(
    'QueueUrl' => $queueUrl,
));

foreach ($result->getPath('Messages/*/Body') as $messageBody) {
    // Do something with the message
    echo $messageBody;
}

// http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sqs.html
```

I received the error of Aws\Commons\Aws is not found, else I write my script with SqsClient and I received thie error below.

```
[Sun Dec 20 09:46:49.937691 2015] [:error] [pid 28131] [client 181.223.98.94:38064] PHP Fatal error:  Uncaught exception 'Aws\\Exception\\CredentialsException' with message 'Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response:\n<?xml version="1.0" encoding="iso-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n         "htt (truncated...)\n)' in /var/www/html/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:79\nStack trace:\n#0 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(199): Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}(Array)\n#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\\Promise\\Promise::callHandler(2, Array, Array)\n#2 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#3 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\\Promise\\TaskQueue->run(true)\n#4 /var/www/html/vend in /var/www/html/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 79
```
This error occured on version 3 of aws sdk php, on version 2, nothing service for sqs.

**Comment by jeskew** [comment]
Hi @IgorDePaula,

It looks like you installed version 3 of the SDK but are reading the instructions for version 2. (The `Aws\Common\Aws` class is only part of version 2 of the SDK, not version 3.) To create a new SQS client, you can either use the `new` keyword:
```php
$sqs = new \Aws\Sqs\SqsClient([
    'version' => '2012-11-05',
    'region' => '<your-preferred-region>',
]);
```
or the `\Aws\Sdk` service locator:
```php
$locator = new \Aws\Sdk([
    'version' => 'latest',
    'region' => '<your-preferred-region>',
]);
$sqs = $locator->createSqs();
```

In either case, you will need to provide AWS credentials to the SDK. (The `\Aws\Exception\CredentialsException` you encountered occurs when no credentials are provided to the SDK, and it attempts to source them from the EC2 Instance Metadata Service.) We have a guide on how to provide credentials and best practices for doing so [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html).

Hope that helps! Please feel free to reopen if you have any questions or concerns.

**Comment by IgorDePaula** [comment]
No, I read both documentation version and pratice with both version, nothing work satisfatory.

**Comment by jeskew** [comment]
The code posted is written for version 2 and the error indicates that version 3 is installed. Have you tried any of the methods listed [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) for providing credentials to the v3 SDK?
