### ISSUE TITLE
hhvm: Fatal Error: Uncaught exception: "Unexpected instance profile response code"

### ISSUE THREAD

**Issue by danielnitz** [aws/aws-sdk-php#973]
This only happens when I run the container within AWS where I don't need to supply any credentials. When I run the same container (on AWS and locally) and supply AWS access key and secret all is fine.

This script fails on hhvm 3.12.1 (but not on php 5.5.33):
```php
<?php
date_default_timezone_set('Europe/Berlin');
require 'vendor/autoload.php';

use Aws\S3\S3Client;

// Instantiate an Amazon S3 client.
$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'eu-west-1'
]);

$s3->putObject([
    'Bucket' => 'my-bucket',
    'Key'    => 'foo.txt',
    'Body'   => 'bla bla'
]);
```

With the following error trace:

```
Warning: json_decode() expects parameter 1 to be string, null given in /app/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 93

Fatal error: Uncaught exception 'Aws\\Exception\\CredentialsException' with message 'Unexpected instance profile response code: ' in /app/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:97
Stack trace:
#0 /app/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\\Credentials\\InstanceProfileProvider->decodeResult()
#1 (): Closure$Aws\\Credentials\\InstanceProfileProvider::__invoke()
#2 /app/vendor/guzzlehttp/promises/src/functions.php(484): Generator->send()
#3 /app/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): Closure$GuzzleHttp\\Promise\\GuzzleHttp\\Promise\\__next_coroutine()
#4 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(61): Closure$GuzzleHttp\\Promise\\FulfilledPromise::then()
#5 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\\Promise\\TaskQueue->run()
#6 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#7 /app/vendor/guzzlehttp/promises/src/Promise.php(242): GuzzleHttp\\Handler\\CurlMultiHandler->execute()
#8 /app/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#9 /app/vendor/guzzlehttp/promises/src/Promise.php(262): GuzzleHttp\\Promise\\Promise->waitIfPending()
#10 /app/vendor/guzzlehttp/promises/src/Promise.php(221): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#11 /app/vendor/guzzlehttp/promises/src/Promise.php(265): GuzzleHttp\\Promise\\Promise->waitIfPending()
#12 /app/vendor/guzzlehttp/promises/src/Promise.php(221): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#13 /app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#14 /app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(59): GuzzleHttp\\Promise\\Promise->wait()
#15 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(208): Aws\\AwsClient->execute()
#16 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(194): Aws\\S3\\S3Client->checkExistenceWithCommand()
#17 /app/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(207): Aws\\S3\\S3Client->doesObjectExist()
#18 /app/vendor/league/flysystem/src/Filesystem.php(54): League\\Flysystem\\AwsS3v3\\AwsS3Adapter->has()
#19 /app/vendor/league/flysystem/src/Filesystem.php(394): League\\Flysystem\\Filesystem->has()
#20 /app/vendor/league/flysystem/src/Filesystem.php(63): League\\Flysystem\\Filesystem->assertAbsent()
#21 /app/public/s3test.php(18): League\\Flysystem\\Filesystem->write()
#22 {main}
```
My versions:
```
$ ./composer.phar info
aws/aws-sdk-php            3.18.1 AWS SDK for PHP - Use Amazon Web Services in your PHP project
guzzlehttp/guzzle          6.2.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises        1.1.0  Guzzle promises library
guzzlehttp/psr7            1.3.0  PSR-7 message implementation
mtdowling/jmespath.php     2.3.0  Declaratively specify how to extract elements from a JSON document
psr/http-message           1.0    Common interface for HTTP messages
```

```
$ php -v
PHP 5.5.33 (cli) (built: Apr  1 2016 22:29:13)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
On Amazon AMI 2016.03 (ami-67a3a90d)

```
$ hhvm --version
HipHop VM 3.12.1 (rel)
Compiler: tags/HHVM-3.12.1-0-gf516f1bb9046218f89885a220354c19dda6d8f4d
Repo schema: f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8
```
On Docker image hhvm/hhvm-proxygen:latest

I verified that I can access the AWS metadata server from within the container in AWS with:
```php
var_dump(file_get_contents("http://169.254.169.254/2014-02-25/dynamic/instance-identity/document"));
```

hhvm.ini
```
; php options

pid = /var/run/hhvm/pid

; hhvm specific 

hhvm.hack.lang.auto_typecheck = 0
hhvm.hack.lang.look_for_typechecker = 0
hhvm.server.port = 80
hhvm.server.type = proxygen 
hhvm.server.default_document = index.php
hhvm.server.error_document404 = index.php
hhvm.server.thread_count= 20
hhvm.server.source_root = /app/public
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.php7.all = 1

; default log location is stdout/err, which is good for docker
hhvm.log.use_log_file = true
```

**Comment by jeskew** [comment]
The instance profile credential provider uses a coroutine, which HHVM does not support due to [a known incompatibility between Zend and HHVM generators](https://github.com/facebook/hhvm/issues/6807). I'm afraid you will need read the instance profile credentials on your own when using HHVM. (This can be can be as simple as `json_decode(file_get_contents('http://169.254.169.254/latest/meta-data/iam/security-credentials/default'))`.)

**Comment by danielnitz** [comment]
@jeskew thank you for getting back this quick and the explanation, very much appreciated.
